### PR TITLE
Command.usableContexts + typings

### PR DESCRIPTION
**Pull request by LJNeon**
See #11, if I missed any typings tell me and I'll update them as well.
Added Command.usableContexts to replace Command.guildOnly and Command.dmOnly.
Minor naming changes to enums for consistency.

### CODE REVIEW

**Comment by ghost** [comment]
You probably missed some typings, but I am not sure which ones. I faintly remember a few typings that weren't implemented even before your big PR's.

**Comment by LJNeon** [comment]
Also just realized that I never updated the Handler to reflect `Command.usableContexts`, I think my mentality was to not touch it at all until the next PR.

**Comment by ghost** [comment]
other than that it seems solid

**Comment by LJNeon** [comment]
I'll go through the docs and try to find which typings it's missing, as well as fix the Handler.

**Pull request merged**
