### PR TITLE
Added support for eris

### PR DESCRIPTION
**Pull request by LJNeon**
This will allow people to use patron.js with eris, and paves the way to use patron.js with the other js libs as well in the future.

This is completely untested and still has a few things that need to be done.

### CODE REVIEW

**Comment by LJNeon** [comment]
So apparently the travis CI build failed because eris/discord.js aren't dependencies so it didn't install them. For now I'm gonna add them both as optional dependencies to imply that only one should be used.

**Comment by ghost** [comment]
make them peer dependencies, optional ones are automatically installed unless the flag --no-optional is added

**Comment by ghost** [comment]
also, no library handler at all in the typings, or else it will appear to be available from the default exports in VSC intellisense, even tho library handler isn't exported. It's only used internally, it should just be a ghost property on the registry, remove from the typings

**Comment by ghost** [comment]
ok, since we only need to apply extensions for the library they are using, put the requireAll inside the registry constructor, and put the lib name as the second foldee inside the extensions, then remove the eris and d.js deps all together

**Comment by LJNeon** [comment]
You might wanna squash merge this so the commits aren't so messy lmao.

**Pull request merged**
