### PR TITLE
Preserve whitespace in remainder arguments.

### PR DESCRIPTION
**Pull request by LJNeon**
See #9. This is fully untested and just an idea of how to solve the problem without requiring additional options or regexes.

### CODE REVIEW

**Comment by ghost** [comment]
Line 113-116 in the handler can be simplified by initially declaring it as the content.

**Comment by LJNeon** [comment]
Fixed

**Comment by LJNeon** [comment]
Came up with an issue with this, if the custom regex for parsing arguments doesn't use whitespace, or even just has something between whitespace like ` | `, (weird but I know bots that do that) this would break.

**Comment by LJNeon** [comment]
Actually had the time to test it, it now works regardless of what the `RegistryOptions.argumentRegex` regex is set to. Now that it's been tested will merge in a week from now if there's no future feedback.

**Comment by LJNeon** [comment]
One hour early, oh well.

**Comment by LJNeon** [comment]
Also if someone somehow makes an argument regex that takes arguments out of order from the message content this would break. But assuming it's safe to gamble on the odds of that happening.

**Pull request merged**
